version: '3.9'

services:
  postgres:
    container_name: task_management_api_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB : tasks_management
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres  
    ports:
      - "5432:5432"  

volumes:
  postgres-db:
    driver: local